

service: e-com-backend

frameworkVersion: "3"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs22.x
  stage: dev
  region: ap-southeast-2

custom:
  serverless-offline:
    noPrependStageInUrl: true
    # This prevents serverless-offline from executing automatic TS compilations
    useChildProcesses: true

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  patterns:
#    - '!exclude-me.js'
#    - '!exclude-me-dir/**'
#    - include-me.js
#    - include-me-dir/**

functions:
  addNewproduct:
    handler: products/addNewproduct.handler
    events:
     - httpApi:
         path: /addNewproduct
         method: post

  getAllproduct:
    handler: products/getAllproduct.handler
    events:
     - httpApi:
         path: /getAllproduct
         method: get

  updateProduct:
    handler: products/updateProduct.handler
    events:
     - httpApi:
         path: /updateProduct/{id}
         method: put

  getProductview:
    handler: products/getProductview.handler
    events:
     - httpApi:
         path: /getProductview
         method: get

  toggleStock:
    handler: products/toggleStock.handler
    events:
     - httpApi:
         path: /toggleStock
         method: put

  deleteProduct:
    handler: products/deleteProduct.handler
    events:
     - httpApi:
         path: /deleteProduct
         method: delete

  addCart:
    handler: cart/addCart.handler
    events:
     - httpApi:
         path: /cart/addCart
         method: post

  getCart:
    handler: cart/getCart.handler
    events:
     - httpApi:
         path: /cart/getCart
         method: get

  removeCart:
    handler: cart/removeCart.handler
    events:
     - httpApi:
         path: /cart/removeCart
         method: delete
  
  updateCart:
    handler: cart/updateCart.handler
    events:
     - httpApi:
         path: /cart/updateCart
         method: update

  signup:
    handler: auth/signup.handler
    events:
     - httpApi:
         path: /auth/signup
         method: post

  upload:
    handler: auth/upload.handler
    events:
     - httpApi:
         path: /upload/upload
         method: post
